# settings.py

"""
Django settings for exam project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d6kzxbx%z&x19&@ut7qz*abh_6^uio5xu$*g2wlx@k+_pu9^v!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exam_app',
    'compressor', 
    'widget_tweaks',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Internationalization
LANGUAGE_CODE = 'th'  # ภาษาไทย
TIME_ZONE = 'Asia/Bangkok'  # ✅ เวลาไทยอย่างถูกต้อง
USE_I18N = True
USE_TZ = True  # ✅ ใช้ timezone
USE_L10N = True

# ✅ เพิ่มการตั้งค่าสำหรับการแสดงวันที่และเวลาในรูปแบบไทย
DATETIME_FORMAT = 'j F Y เวลา H:i น.'
DATE_FORMAT = 'j F Y'
TIME_FORMAT = 'H:i น.'

# ✅ ตั้งค่าการจัดรูปแบบวันที่สำหรับ input
DATETIME_INPUT_FORMATS = [
    '%Y-%m-%d %H:%M',
    '%Y-%m-%d %H:%M:%S',
    '%d/%m/%Y %H:%M',
    '%d/%m/%Y %H:%M:%S',
]

DATE_INPUT_FORMATS = [
    '%Y-%m-%d',
    '%d/%m/%Y',
    '%d-%m-%Y',
]

TIME_INPUT_FORMATS = [
    '%H:%M',
    '%H:%M:%S',
]

# ✅ ตั้งค่าภาษาไทยสำหรับ datetime
import locale
try:
    locale.setlocale(locale.LC_TIME, 'th_TH.UTF-8')  # Linux/Mac
except:
    try:
        locale.setlocale(locale.LC_TIME, 'Thai_Thailand.874')  # Windows
    except:
        pass  # ใช้ default ถ้าไม่ได้

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [BASE_DIR / 'static', ]
STATIC_ROOT = BASE_DIR / 'staticfiles'
COMPRESS_ROOT = BASE_DIR / 'static'
 
# COMPRESS_ENABLED = True
 
# STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'exam_app.User'

# AUTH_USER_MODEL = 'exam_app.Teacher'

MEDIA_URL = '/media/'  # การเข้าถึงไฟล์มีเดียผ่าน URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # ที่เก็บไฟล์มีเดียในระบบ