# Generated by Django 5.0.1 on 2024-02-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Maximum number of students that can be accommodated.')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=4)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exam_app.studentprofile')),
                ('exam_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.examroom')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='exam_app.teacherprofile')),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to='exam_app.teacherprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
