# Generated by Django 5.2.1 on 2025-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, default='เจ้าหน้าที่', max_length=50, verbose_name='ตำแหน่ง'),
        ),
    ]
