# Generated by Django 5.2.1 on 2025-07-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_staffprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject_expertise',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(max_length=10, verbose_name='เลขที่'),
        ),
    ]
