# Generated by Django 5.0.1 on 2024-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_rename_class_level_examsubject_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_group',
            field=models.CharField(choices=[('math', 'กลุ่มสาระการเรียนรู้คณิตศาสตร์'), ('science', 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์และเทคโนโลยี'), ('thai', 'กลุ่มสาระการเรียนรู้ภาษาไทย'), ('foreign_language', 'กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ'), ('social', 'กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนาและวัฒนธรรม'), ('physical_education', 'กลุ่มสาระการเรียนรู้สุขศึกษา พลศึกษา'), ('art', 'กลุ่มสาระการเรียนรู้ศิลปศึกษา'), ('career', 'กลุ่มสาระการเรียนรู้การงานอาชีพ')], default='', max_length=100),
        ),
    ]
