# Generated by Django 5.2.1 on 2025-08-24 14:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20250824_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_class', 'student_number'], 'verbose_name': 'โปรไฟล์นักเรียน', 'verbose_name_plural': 'โปรไฟล์นักเรียน'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'โปรไฟล์ครู', 'verbose_name_plural': 'โปรไฟล์ครู'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
        migrations.RemoveField(
            model_name='examroom',
            name='has_aircon',
        ),
        migrations.RemoveField(
            model_name='examroom',
            name='has_projector',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ใช้งานได้'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='แผนก/กลุ่มสาระ'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('on_time', 'มาตรงเวลา'), ('late', 'มาสาย'), ('absent', 'ขาดสอบ'), ('excused', 'ลาป่วย/ลากิจ'), ('cheating', 'ทุจริต')], default='absent', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='exam_app.studentprofile', verbose_name='นักเรียน'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='exam_app.examsubject', verbose_name='รายวิชา'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่ออาคาร'),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='ความจุ'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='academic_year',
            field=models.CharField(max_length=10, verbose_name='ปีการศึกษา'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_exam_subjects', to='exam_app.teacherprofile', verbose_name='ครูคุมสอบหลัก'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subjects', to='exam_app.examroom', verbose_name='ห้องสอบ'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='secondary_invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_exam_subjects', to='exam_app.teacherprofile', verbose_name='ครูคุมสอบสำรอง'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='subject_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(default='เจ้าหน้าที่', max_length=50, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='รหัสเจ้าหน้าที่'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_number',
            field=models.PositiveIntegerField(verbose_name='เลขที่'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('student_class', 'student_number')},
        ),
        migrations.CreateModel(
            name='CheatingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheating_type', models.CharField(choices=[('copying', 'ลอกข้อสอบ'), ('communication', 'สื่อสารกับผู้อื่น'), ('materials', 'นำสื่อการสอนเข้าห้องสอบ'), ('technology', 'ใช้อุปกรณ์อิเล็กทรอนิกส์'), ('impersonation', 'สอบแทนกัน'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทการทุจริต')),
                ('description', models.TextField(verbose_name='รายละเอียดการทุจริต')),
                ('action_taken', models.TextField(verbose_name='มาตรการที่ดำเนินการ')),
                ('witness', models.CharField(blank=True, max_length=200, verbose_name='พยาน')),
                ('status', models.CharField(choices=[('reported', 'รายงานแล้ว'), ('investigating', 'กำลังสอบสวน'), ('confirmed', 'ยืนยันทุจริต'), ('dismissed', 'ยกเลิกข้อหา'), ('resolved', 'ดำเนินการเสร็จสิ้น')], default='reported', max_length=15, verbose_name='สถานะการดำเนินการ')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='หมายเหตุการสอบสวน')),
                ('final_decision', models.TextField(blank=True, verbose_name='คำตัดสินสุดท้าย')),
                ('penalty', models.CharField(blank=True, max_length=100, verbose_name='โทษที่ได้รับ')),
                ('evidence_files', models.FileField(blank=True, null=True, upload_to='cheating_evidence/', verbose_name='เอกสารหลักฐาน')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ดำเนินการเสร็จ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่รายงาน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_report', to='exam_app.attendance', verbose_name='การเข้าสอบ')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cheating_cases', to=settings.AUTH_USER_MODEL, verbose_name='รายงานโดย')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cheating_cases', to=settings.AUTH_USER_MODEL, verbose_name='ดำเนินการโดย')),
            ],
            options={
                'verbose_name': 'รายงานทุจริต',
                'verbose_name_plural': 'รายงานทุจริต',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheatingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ปี')),
                ('month', models.IntegerField(verbose_name='เดือน')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='จำนวนคดีทั้งหมด')),
                ('resolved_cases', models.PositiveIntegerField(default=0, verbose_name='คดีที่ดำเนินการเสร็จ')),
                ('confirmed_cases', models.PositiveIntegerField(default=0, verbose_name='คดีที่ยืนยันทุจริต')),
                ('dismissed_cases', models.PositiveIntegerField(default=0, verbose_name='คดีที่ยกเลิก')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'สถิติการทุจริต',
                'verbose_name_plural': 'สถิติการทุจริต',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='เริ่มสอบเมื่อ')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='จบสอบเมื่อ')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='จำนวนนักเรียนทั้งหมด')),
                ('present_students', models.PositiveIntegerField(default=0, verbose_name='จำนวนนักเรียนที่มา')),
                ('absent_students', models.PositiveIntegerField(default=0, verbose_name='จำนวนนักเรียนที่ขาด')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุการสอบ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exam_app.examsubject', verbose_name='วิชาสอบ')),
            ],
            options={
                'verbose_name': 'เซสชันการสอบ',
                'verbose_name_plural': 'เซสชันการสอบ',
                'ordering': ['-created_at'],
            },
        ),
    ]
