# Generated by Django 5.0.1 on 2025-01-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam_app', '0004_remove_user_unique_username_per_school_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'school_name'), name='unique_username_per_school'),
        ),
    ]
