# Generated by Django 5.0.1 on 2024-02-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_alter_teacherprofile_subject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject_group',
        ),
        migrations.AlterField(
            model_name='news',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='exam_app.studentprofile'),
        ),
    ]
