# Generated by Django 5.0.1 on 2025-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(max_length=20),
        ),
    ]
