# Generated by Django 5.2.1 on 2025-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroom',
            name='has_aircon',
            field=models.BooleanField(default=False, verbose_name='มีแอร์'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='has_projector',
            field=models.BooleanField(default=False, verbose_name='มีโปรเจคเตอร์'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(max_length=10, verbose_name='เลขที่'),
        ),
    ]
