# Generated by Django 5.2.1 on 2025-09-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_examroom_has_aircon_examroom_has_projector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingreport',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='cheatingreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='cheatingreport',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='CheatingStatistics',
        ),
        migrations.RemoveField(
            model_name='examroom',
            name='has_aircon',
        ),
        migrations.RemoveField(
            model_name='examroom',
            name='has_projector',
        ),
        migrations.DeleteModel(
            name='CheatingReport',
        ),
    ]
