# Generated by Django 5.0.1 on 2024-02-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_alter_examsubject_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exam_app.studentprofile'),
        ),
    ]
