# Generated by Django 5.0.1 on 2025-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_remove_attendance_exam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('teacher_id', 'school_name'), name='unique_teacher_per_school'),
        ),
    ]
