# Generated by Django 5.0.1 on 2025-01-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_teacherprofile_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('academic_year', models.CharField(max_length=4)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='exam_app.teacherprofile', verbose_name='ผู้คุมสอบ')),
                ('students', models.ManyToManyField(blank=True, related_name='exam_subjects', to='exam_app.studentprofile', verbose_name='นักเรียน')),
            ],
        ),
    ]
