# Generated by Django 5.0 on 2024-02-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_qrtoken_seatassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='registered_exams', to='exam_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects_class', to='exam_app.studentprofile'),
        ),
    ]
