# Generated by Django 5.0.1 on 2025-02-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_examsubject_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_time', 'มาตรงเวลา'), ('late', 'มาสาย'), ('absent', 'ขาดสอบ')], default='absent', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.examsubject')),
            ],
        ),
    ]
