# Generated by Django 5.0.1 on 2025-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='columns',
            field=models.PositiveIntegerField(default=5, verbose_name='จำนวนที่นั่งต่อแถว'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='rows',
            field=models.PositiveIntegerField(default=5, verbose_name='จำนวนแถว'),
        ),
    ]
