# Generated by Django 5.1.6 on 2025-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_examsubject_columns_examsubject_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='invigilator_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
