# Generated by Django 5.1.6 on 2025-02-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0015_seatingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubject',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='examsubject',
            name='rows',
        ),
        migrations.DeleteModel(
            name='SeatingPlan',
        ),
    ]
