# Generated by Django 5.1.6 on 2025-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0016_remove_examsubject_columns_remove_examsubject_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
