# Generated by Django 5.1.6 on 2025-03-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0017_staffprofile_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='secondary_invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_invigilated_exams', to='exam_app.teacherprofile', verbose_name='ผู้คุมสอบสำรอง'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='exam_app.teacherprofile', verbose_name='ผู้คุมสอบหลัก'),
        ),
    ]
