# Generated by Django 5.1.6 on 2025-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0019_examsubject_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'school_name'), name='unique_subject_code_per_school'),
        ),
    ]
