# Generated by Django 5.1.6 on 2025-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0020_alter_examsubject_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='qr_expiration',
            field=models.TimeField(blank=True, help_text='เวลาที่ QR Code หมดอายุ (ตัวอย่าง: 14:30)', null=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='secondary_invigilator_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
