# Generated by Django 5.1.6 on 2025-05-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0022_examsubject_invigilator_checkin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อห้อง')),
                ('capacity', models.PositiveIntegerField(verbose_name='ความจุ')),
            ],
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='qr_expiration',
            field=models.TimeField(blank=True, help_text='เวลาที่ QR Code หมดอายุ', null=True),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.examroom', verbose_name='ห้องสอบ'),
        ),
    ]
