# Generated by Django 5.1.6 on 2025-05-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0023_examroom_alter_examsubject_qr_expiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='examroom',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='examroom',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='exam_app.building'),
        ),
        migrations.AlterUniqueTogether(
            name='examroom',
            unique_together={('building', 'name')},
        ),
    ]
