# Generated by Django 5.1.6 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0024_building_alter_examroom_capacity_alter_examroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
