# Generated by Django 5.1.6 on 2025-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0025_alter_examsubject_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
