# Generated by Django 5.2.1 on 2025-06-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0026_alter_examsubject_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='term',
            field=models.CharField(choices=[('1', 'เทอม 1'), ('2', 'เทอม 2'), ('3', 'เทอม 3')], default='1', max_length=1),
        ),
    ]
