# Generated by Django 5.2.1 on 2025-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0027_examsubject_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='academic_year',
            field=models.CharField(max_length=5),
        ),
    ]
