# Generated by Django 5.2.1 on 2025-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0028_alter_examsubject_academic_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examsubject',
            name='unique_subject_code_per_school',
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'school_name', 'academic_year', 'term'), name='unique_subject_per_school_year_term'),
        ),
    ]
