# Generated by Django 5.2.1 on 2025-06-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0029_remove_examsubject_unique_subject_code_per_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='end_time',
            field=models.DateTimeField(verbose_name='เวลาสิ้นสุดสอบ'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='start_time',
            field=models.DateTimeField(verbose_name='เวลาเริ่มสอบ'),
        ),
    ]
