# Generated by Django 5.2.1 on 2025-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0030_alter_examsubject_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
